namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Acro
		Formatted Name: Acro
		Emotion Count: 5
*/
public class Acro : Character<Acro.AcroEmotions>
{
	public enum AcroEmotions
	{
		Cry = 322,
		Sad = 325,
		Serious = 324,
		Smile = 323,
		Stand = 326
	}

	public const string RawName = "Acro";

	public Acro(string username, AcroEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}