namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Adrian Andrews
		Formatted Name: AdrianAndrews
		Emotion Count: 10
*/
public class AdrianAndrews : Character<AdrianAndrews.AdrianAndrewsEmotions>
{
	public enum AdrianAndrewsEmotions
	{
		Broken = 553,
		Cornered = 554,
		Damage = 550,
		Happy = 552,
		Read = 556,
		Sad = 551,
		Serious = 555,
		Stand = 557,
		Surprised = 558,
		Think = 559
	}

	public const string RawName = "Adrian Andrews";

	public AdrianAndrews(string username, AdrianAndrewsEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}