namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: April May
		Formatted Name: AprilMay
		Emotion Count: 10
*/
public class AprilMay : Character<AprilMay.AprilMayEmotions>
{
	public enum AprilMayEmotions
	{
		Angry = 314,
		AngryLookAway = 315,
		AngryStare = 313,
		Annoyed = 316,
		Cry = 319,
		Rage = 317,
		Scared = 318,
		Stand = 481,
		Think = 321,
		Wink = 320
	}

	public const string RawName = "April May";

	public AprilMay(string username, AprilMayEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}