namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: BellBoy
		Formatted Name: BellBoy
		Emotion Count: 2
*/
public class BellBoy : Character<BellBoy.BellBoyEmotions>
{
	public enum BellBoyEmotions
	{
		Shy = 548,
		Stand = 549
	}

	public const string RawName = "BellBoy";

	public BellBoy(string username, BellBoyEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}