namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Benjamin & Trilo
		Formatted Name: BenjaminTrilo
		Emotion Count: 8
*/
public class BenjaminTrilo : Character<BenjaminTrilo.BenjaminTriloEmotions>
{
	public enum BenjaminTriloEmotions
	{
		Angry = 639,
		Confident = 638,
		Damage = 634,
		LookAway = 633,
		Stand = 636,
		StandWithTrilo = 640,
		TriloPunch = 635,
		TriloPunch2 = 637
	}

	public const string RawName = "Benjamin & Trilo";

	public BenjaminTrilo(string username, BenjaminTriloEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}