namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Bikini
		Formatted Name: Bikini
		Emotion Count: 8
*/
public class Bikini : Character<Bikini.BikiniEmotions>
{
	public enum BikiniEmotions
	{
		Happy = 642,
		Laugh = 641,
		Laugh2 = 646,
		Sad = 648,
		Scared = 647,
		Serious = 644,
		Stand = 643,
		Think = 645
	}

	public const string RawName = "Bikini";

	public Bikini(string username, BikiniEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}