using RandomGameBot.Features.ObjectionLol.Wrapper;

namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Info:
		Total Character Count: 101
*/
public abstract class Character<T>
{
	public T Emotion;
	public string Text;
	public string Username;

	public Character(string username, T emotion, string text)
	{
		Username = username;
		Emotion = emotion;
		Text = text;
	}

	public Frame ToFrame(int iid)
	{
		return new Frame
		{
			iid = iid,
			text = Text,
			poseId = Convert.ToInt32(Emotion),
			username = Username
		};
	}
}