namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Cody Hackins
		Formatted Name: CodyHackins
		Emotion Count: 9
*/
public class CodyHackins : Character<CodyHackins.CodyHackinsEmotions>
{
	public enum CodyHackinsEmotions
	{
		Angry = 278,
		Annoyed = 276,
		Confident = 279,
		Cry = 284,
		Crying = 281,
		Happy = 280,
		Sad = 282,
		Stand = 277,
		Surprised = 283
	}

	public const string RawName = "Cody Hackins";

	public CodyHackins(string username, CodyHackinsEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}