namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Damon Gant
		Formatted Name: DamonGant
		Emotion Count: 11
*/
public class DamonGant : Character<DamonGant.DamonGantEmotions>
{
	public enum DamonGantEmotions
	{
		Breakdown1 = 95,
		Breakdown2 = 749,
		Clap = 92,
		Cornered = 96,
		Damage = 93,
		Impatient = 97,
		Smile = 99,
		Smirking = 98,
		Stand = 94,
		StandEyesClosed = 312,
		Wondering = 311
	}

	public const string RawName = "Damon Gant";

	public DamonGant(string username, DamonGantEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}