namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Daryan Crescend
		Formatted Name: DaryanCrescend
		Emotion Count: 11
*/
public class DaryanCrescend : Character<DaryanCrescend.DaryanCrescendEmotions>
{
	public enum DaryanCrescendEmotions
	{
		Angry = 735,
		ArmsCrossed = 734,
		Breakdown = 736,
		Broken = 738,
		Cornered = 741,
		Damage = 740,
		Damage2 = 742,
		HairPlay = 744,
		Laugh = 743,
		Stand = 737,
		Surprised = 739
	}

	public const string RawName = "Daryan Crescend";

	public DaryanCrescend(string username, DaryanCrescendEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}