namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Dee Vasquez
		Formatted Name: DeeVasquez
		Emotion Count: 8
*/
public class DeeVasquez : Character<DeeVasquez.DeeVasquezEmotions>
{
	public enum DeeVasquezEmotions
	{
		Breakdown = 432,
		Confident = 426,
		Cornered = 428,
		Damage = 429,
		EyesClosed = 431,
		Happy = 430,
		Stand = 427,
		Surprised = 433
	}

	public const string RawName = "Dee Vasquez";

	public DeeVasquez(string username, DeeVasquezEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}