namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Diego Armando
		Formatted Name: DiegoArmando
		Emotion Count: 4
*/
public class DiegoArmando : Character<DiegoArmando.DiegoArmandoEmotions>
{
	public enum DiegoArmandoEmotions
	{
		BreakCup = 91,
		Stand = 46,
		Stand2 = 45,
		Stand3 = 417
	}

	public const string RawName = "Diego Armando";

	public DiegoArmando(string username, DiegoArmandoEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}