namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Director Hotti
		Formatted Name: DirectorHotti
		Emotion Count: 3
*/
public class DirectorHotti : Character<DirectorHotti.DirectorHottiEmotions>
{
	public enum DirectorHottiEmotions
	{
		Crazy = 673,
		Stand = 672,
		Whisper = 674
	}

	public const string RawName = "Director Hotti";

	public DirectorHotti(string username, DirectorHottiEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}