namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Drew Misham
		Formatted Name: DrewMisham
		Emotion Count: 4
*/
public class DrewMisham : Character<DrewMisham.DrewMishamEmotions>
{
	public enum DrewMishamEmotions
	{
		Cornered = 656,
		Sad = 655,
		Stand = 658,
		Think = 657
	}

	public const string RawName = "Drew Misham";

	public DrewMisham(string username, DrewMishamEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}