namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Elise Deauxnim
		Formatted Name: EliseDeauxnim
		Emotion Count: 2
*/
public class EliseDeauxnim : Character<EliseDeauxnim.EliseDeauxnimEmotions>
{
	public enum EliseDeauxnimEmotions
	{
		Happy = 678,
		Stand = 679
	}

	public const string RawName = "Elise Deauxnim";

	public EliseDeauxnim(string username, EliseDeauxnimEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}