namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Franziska von Karma
		Formatted Name: FranziskaVonKarma
		Emotion Count: 11
*/
public class FranziskaVonKarma : Character<FranziskaVonKarma.FranziskaVonKarmaEmotions>
{
	public enum FranziskaVonKarmaEmotions
	{
		ArmsCrossed = 274,
		Bow = 26,
		Confident = 21,
		Cornered = 25,
		Damage = 23,
		DamageCustom = 411,
		DeskSlam = 192,
		Point = 41,
		Stand = 22,
		WhipDesk = 193,
		Yell = 24
	}

	public const string RawName = "Franziska von Karma";

	public FranziskaVonKarma(string username, FranziskaVonKarmaEmotions emotion, string text) : base(username, emotion,
		text)
	{
	}
}