namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Frank Sahwit
		Formatted Name: FrankSahwit
		Emotion Count: 7
*/
public class FrankSahwit : Character<FrankSahwit.FrankSahwitEmotions>
{
	public enum FrankSahwitEmotions
	{
		Angry = 399,
		Breakdown = 71,
		Cornered = 72,
		Damage = 73,
		Nervous = 75,
		Stand = 400,
		Throw = 74
	}

	public const string RawName = "Frank Sahwit";

	public FrankSahwit(string username, FrankSahwitEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}