namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Furio Tigre
		Formatted Name: FurioTigre
		Emotion Count: 9
*/
public class FurioTigre : Character<FurioTigre.FurioTigreEmotions>
{
	public enum FurioTigreEmotions
	{
		Angry = 285,
		Breakdown1 = 291,
		Breakdown2 = 286,
		Compliant = 289,
		Cornered = 290,
		Roar = 288,
		Shameless = 293,
		Simper = 292,
		Stand = 287
	}

	public const string RawName = "Furio Tigre";

	public FurioTigre(string username, FurioTigreEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}