namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Gallery (AJ)
		Formatted Name: GalleryAJ
		Emotion Count: 3
*/
public class GalleryAJ : Character<GalleryAJ.GalleryAJEmotions>
{
	public enum GalleryAJEmotions
	{
		EmptyAudience = 747,
		Idle = 746,
		Talk = 748
	}

	public const string RawName = "Gallery (AJ)";

	public GalleryAJ(string username, GalleryAJEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}