namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Godot
		Formatted Name: Godot
		Emotion Count: 16
*/
public class Godot : Character<Godot.GodotEmotions>
{
	public enum GodotEmotions
	{
		Confident = 275,
		ConfidentWithMug = 219,
		Cornered = 182,
		Damage = 175,
		DamageCustom = 177,
		DeskSlam = 178,
		DeskSlamWithMug = 176,
		MaskExplosion = 184,
		MugSip = 520,
		NewMugSip = 173,
		Point = 174,
		PointWithMug = 413,
		Stand = 218,
		Think = 179,
		ThrowMug = 181,
		Yell = 180
	}

	public const string RawName = "Godot";

	public Godot(string username, GodotEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}