namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Guy Eldoon
		Formatted Name: GuyEldoon
		Emotion Count: 9
*/
public class GuyEldoon : Character<GuyEldoon.GuyEldoonEmotions>
{
	public enum GuyEldoonEmotions
	{
		Cornered = 659,
		EyesClosed = 663,
		Forceful = 667,
		Harmonica = 665,
		HatOff = 666,
		HatOn = 662,
		Serious = 660,
		Slump = 661,
		Stand = 664
	}

	public const string RawName = "Guy Eldoon";

	public GuyEldoon(string username, GuyEldoonEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}