namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Ini Miney
		Formatted Name: IniMiney
		Emotion Count: 9
*/
public class IniMiney : Character<IniMiney.IniMineyEmotions>
{
	public enum IniMineyEmotions
	{
		Angry = 246,
		Confident = 245,
		Cornered = 247,
		Damage = 252,
		Possessed = 480,
		Sad = 249,
		Silly = 250,
		Stand = 248,
		Think = 251
	}

	public const string RawName = "Ini Miney";

	public IniMiney(string username, IniMineyEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}