namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Iris
		Formatted Name: Iris
		Emotion Count: 14
*/
public class Iris : Character<Iris.IrisEmotions>
{
	public enum IrisEmotions
	{
		Angry = 262,
		Broken = 263,
		Cornered = 261,
		Cry = 267,
		Damage = 266,
		HairPlay = 488,
		Happy = 487,
		Maya = 265,
		Maya2 = 485,
		Neutral = 268,
		Smirk = 264,
		Stand = 269,
		Surprised = 486,
		Uncertain = 270
	}

	public const string RawName = "Iris";

	public Iris(string username, IrisEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}