namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Jake Marshall
		Formatted Name: JakeMarshall
		Emotion Count: 10
*/
public class JakeMarshall : Character<JakeMarshall.JakeMarshallEmotions>
{
	public enum JakeMarshallEmotions
	{
		Cornered = 152,
		Damage = 162,
		Drink = 159,
		DrinkNewBottle = 153,
		HatOff = 157,
		Nervous = 156,
		Point = 154,
		Serious = 155,
		Shave = 160,
		Stand = 161
	}

	public const string RawName = "Jake Marshall";

	public JakeMarshall(string username, JakeMarshallEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}