namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Jean Armstrong
		Formatted Name: JeanArmstrong
		Emotion Count: 7
*/
public class JeanArmstrong : Character<JeanArmstrong.JeanArmstrongEmotions>
{
	public enum JeanArmstrongEmotions
	{
		Cornered = 491,
		Damage = 489,
		Dance = 494,
		Happy = 490,
		Sad = 495,
		Stand = 493,
		Think = 492
	}

	public const string RawName = "Jean Armstrong";

	public JeanArmstrong(string username, JeanArmstrongEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}