namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Klavier Gavin
		Formatted Name: KlavierGavin
		Emotion Count: 12
*/
public class KlavierGavin : Character<KlavierGavin.KlavierGavinEmotions>
{
	public enum KlavierGavinEmotions
	{
		AirGuitar = 689,
		Cornered = 217,
		Cornered2 = 67,
		Damage = 65,
		DamageCustom = 66,
		Laugh = 70,
		LookUp = 68,
		Point = 414,
		Stand = 401,
		Think = 745,
		WallSlam = 64,
		Yell = 69
	}

	public const string RawName = "Klavier Gavin";

	public KlavierGavin(string username, KlavierGavinEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}