namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Kristoph Gavin
		Formatted Name: KristophGavin
		Emotion Count: 3
*/
public class KristophGavin : Character<KristophGavin.KristophGavinEmotions>
{
	public enum KristophGavinEmotions
	{
		Side = 458,
		Smile = 460,
		Stand = 459
	}

	public const string RawName = "Kristoph Gavin";

	public KristophGavin(string username, KristophGavinEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}