namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Kristoph Gavin (with badge)
		Formatted Name: KristophGavinWithBadge
		Emotion Count: 13
*/
public class KristophGavinWithBadge : Character<KristophGavinWithBadge.KristophGavinWithBadgeEmotions>
{
	public enum KristophGavinWithBadgeEmotions
	{
		Angry = 517,
		Annoyed = 508,
		Confident = 510,
		Damage = 511,
		Damage2 = 509,
		DeskSlam = 521,
		Evil = 522,
		Glare = 518,
		Headshake = 515,
		Mysterious = 514,
		Smile = 512,
		Stand = 513,
		Uneasy = 516
	}

	public const string RawName = "Kristoph Gavin (with badge)";

	public KristophGavinWithBadge(string username, KristophGavinWithBadgeEmotions emotion, string text) : base(username,
		emotion, text)
	{
	}
}