namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Lana Skye
		Formatted Name: LanaSkye
		Emotion Count: 12
*/
public class LanaSkye : Character<LanaSkye.LanaSkyeEmotions>
{
	public enum LanaSkyeEmotions
	{
		Cornered = 199,
		Damage = 196,
		FaceBehind = 195,
		FaceBehindMovement = 194,
		FaceFrontMovement = 205,
		FaceSide = 204,
		Happy = 200,
		Serious = 203,
		Stand = 202,
		Stand2 = 201,
		Stand3 = 198,
		Surprised = 197
	}

	public const string RawName = "Lana Skye";

	public LanaSkye(string username, LanaSkyeEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}