namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Lisa Basil
		Formatted Name: LisaBasil
		Emotion Count: 3
*/
public class LisaBasil : Character<LisaBasil.LisaBasilEmotions>
{
	public enum LisaBasilEmotions
	{
		Cornered = 675,
		Happy = 676,
		Stand = 677
	}

	public const string RawName = "Lisa Basil";

	public LisaBasil(string username, LisaBasilEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}