namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Lotta Hart
		Formatted Name: LottaHart
		Emotion Count: 9
*/
public class LottaHart : Character<LottaHart.LottaHartEmotions>
{
	public enum LottaHartEmotions
	{
		Angry = 120,
		Damage = 119,
		Relieved = 114,
		Silly = 113,
		Smile = 117,
		Stand = 115,
		Stand2 = 116,
		Stare = 478,
		Uncertain = 118
	}

	public const string RawName = "Lotta Hart";

	public LottaHart(string username, LottaHartEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}