namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Luke Atmey
		Formatted Name: LukeAtmey
		Emotion Count: 10
*/
public class LukeAtmey : Character<LukeAtmey.LukeAtmeyEmotions>
{
	public enum LukeAtmeyEmotions
	{
		Breakdown = 240,
		Cornered = 234,
		Crazy = 235,
		Damage = 237,
		Laugh = 236,
		LookUp = 242,
		Magnify = 239,
		ShineRing = 241,
		Stand = 238,
		WipeMagnifier = 243
	}

	public const string RawName = "Luke Atmey";

	public LukeAtmey(string username, LukeAtmeyEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}