namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Maggey Byrde
		Formatted Name: MaggeyByrde
		Emotion Count: 2
*/
public class MaggeyByrde : Character<MaggeyByrde.MaggeyByrdeEmotions>
{
	public enum MaggeyByrdeEmotions
	{
		Pumped = 369,
		Stand = 370
	}

	public const string RawName = "Maggey Byrde";

	public MaggeyByrde(string username, MaggeyByrdeEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}