namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Manfred von Karma
		Formatted Name: ManfredVonKarma
		Emotion Count: 9
*/
public class ManfredVonKarma : Character<ManfredVonKarma.ManfredVonKarmaEmotions>
{
	public enum ManfredVonKarmaEmotions
	{
		ArmsCrossed = 27,
		Breakdown1 = 43,
		Breakdown2 = 412,
		Confident = 191,
		Cornered = 42,
		Damage = 28,
		DamageCustom = 310,
		SnapFinger = 309,
		Stand = 29
	}

	public const string RawName = "Manfred von Karma";

	public ManfredVonKarma(string username, ManfredVonKarmaEmotions emotion, string text) : base(username, emotion,
		text)
	{
	}
}