namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Maximillion Galactica
		Formatted Name: MaximillionGalactica
		Emotion Count: 5
*/
public class MaximillionGalactica : Character<MaximillionGalactica.MaximillionGalacticaEmotions>
{
	public enum MaximillionGalacticaEmotions
	{
		Confident = 579,
		Cornered = 580,
		Cry = 583,
		Point = 582,
		Stand = 581
	}

	public const string RawName = "Maximillion Galactica";

	public MaximillionGalactica(string username, MaximillionGalacticaEmotions emotion, string text) : base(username,
		emotion, text)
	{
	}
}