namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Mia (as Maya)
		Formatted Name: MiaAsMaya
		Emotion Count: 5
*/
public class MiaAsMaya : Character<MiaAsMaya.MiaAsMayaEmotions>
{
	public enum MiaAsMayaEmotions
	{
		Angry = 725,
		Dull = 726,
		Headshake = 727,
		Nod = 728,
		Stand = 729
	}

	public const string RawName = "Mia (as Maya)";

	public MiaAsMaya(string username, MiaAsMayaEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}