namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Miles Edgeworth (young)
		Formatted Name: MilesEdgeworthYoung
		Emotion Count: 8
*/
public class MilesEdgeworthYoung : Character<MilesEdgeworthYoung.MilesEdgeworthYoungEmotions>
{
	public enum MilesEdgeworthYoungEmotions
	{
		ArmsCrossed = 10,
		Confident = 12,
		Cornered = 11,
		Damage = 408,
		DamageCustom = 141,
		DeskSlam = 37,
		Point = 14,
		Stand = 13
	}

	public const string RawName = "Miles Edgeworth (young)";

	public MilesEdgeworthYoung(string username, MilesEdgeworthYoungEmotions emotion, string text) : base(username,
		emotion, text)
	{
	}
}