namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Miles Edgeworth (defense)
		Formatted Name: MilesEdgeworthDefense
		Emotion Count: 12
*/
public class MilesEdgeworthDefense : Character<MilesEdgeworthDefense.MilesEdgeworthDefenseEmotions>
{
	public enum MilesEdgeworthDefenseEmotions
	{
		ArmsCrossed = 701,
		ConfidentShrug = 690,
		ConfidentSmirk = 697,
		Cornered = 698,
		Damage = 692,
		DamageCustom = 691,
		DeskSlam = 700,
		Point = 699,
		Read = 695,
		Smirk = 696,
		Stand = 694,
		Yell = 693
	}

	public const string RawName = "Miles Edgeworth (defense)";

	public MilesEdgeworthDefense(string username, MilesEdgeworthDefenseEmotions emotion, string text) : base(username,
		emotion, text)
	{
	}
}