namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Moe
		Formatted Name: Moe
		Emotion Count: 7
*/
public class Moe : Character<Moe.MoeEmotions>
{
	public enum MoeEmotions
	{
		Angry = 572,
		Damage = 578,
		Dull = 575,
		Laugh = 573,
		Point = 574,
		Sad = 576,
		Stand = 577
	}

	public const string RawName = "Moe";

	public Moe(string username, MoeEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}