namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Morgan Fey
		Formatted Name: MorganFey
		Emotion Count: 4
*/
public class MorganFey : Character<MorganFey.MorganFeyEmotions>
{
	public enum MorganFeyEmotions
	{
		Angry = 544,
		Sad = 545,
		Sleeve = 546,
		Stand = 547
	}

	public const string RawName = "Morgan Fey";

	public MorganFey(string username, MorganFeyEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}