namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Pearl Fey
		Formatted Name: PearlFey
		Emotion Count: 9
*/
public class PearlFey : Character<PearlFey.PearlFeyEmotions>
{
	public enum PearlFeyEmotions
	{
		Angry = 471,
		Cry = 474,
		Dream = 469,
		Happy = 476,
		Neutral = 470,
		Sad = 473,
		Stand = 475,
		Surprised = 477,
		Worried = 472
	}

	public const string RawName = "Pearl Fey";

	public PearlFey(string username, PearlFeyEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}