namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Penny Nichols
		Formatted Name: PennyNichols
		Emotion Count: 3
*/
public class PennyNichols : Character<PennyNichols.PennyNicholsEmotions>
{
	public enum PennyNicholsEmotions
	{
		Cards = 630,
		Confident = 631,
		Stand = 632
	}

	public const string RawName = "Penny Nichols";

	public PennyNichols(string username, PennyNicholsEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}