namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Phoenix Wright (old)
		Formatted Name: PhoenixWrightOld
		Emotion Count: 4
*/
public class PhoenixWrightOld : Character<PhoenixWrightOld.PhoenixWrightOldEmotions>
{
	public enum PhoenixWrightOldEmotions
	{
		Confident = 434,
		Point = 436,
		Serious = 437,
		Stand = 435
	}

	public const string RawName = "Phoenix Wright (old)";

	public PhoenixWrightOld(string username, PhoenixWrightOldEmotions emotion, string text) : base(username, emotion,
		text)
	{
	}
}