namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Phoenix Wright
		Formatted Name: PhoenixWright
		Emotion Count: 18
*/
public class PhoenixWright : Character<PhoenixWright.PhoenixWrightEmotions>
{
	public enum PhoenixWrightEmotions
	{
		Breakdown = 271,
		CoffeeStained = 33,
		Confident = 519,
		Cornered = 1,
		Damage = 76,
		DamageCustom = 35,
		DeskSlam = 59,
		HairStained = 3,
		Headshake = 100,
		Nod = 101,
		Point = 358,
		Read = 2,
		Silly = 406,
		SipMug = 129,
		Stand = 34,
		SuperObjection = 4,
		Thinking = 188,
		Yell = 140
	}

	public const string RawName = "Phoenix Wright";

	public PhoenixWright(string username, PhoenixWrightEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}