namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Polly
		Formatted Name: Polly
		Emotion Count: 1
*/
public class Polly : Character<Polly.PollyEmotions>
{
	public enum PollyEmotions
	{
		Stand = 302
	}

	public const string RawName = "Polly";

	public Polly(string username, PollyEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}