namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Regina Berry
		Formatted Name: ReginaBerry
		Emotion Count: 8
*/
public class ReginaBerry : Character<ReginaBerry.ReginaBerryEmotions>
{
	public enum ReginaBerryEmotions
	{
		Cry = 299,
		Happy = 294,
		Point = 298,
		Sad = 297,
		Sparkle = 300,
		Sparkle2 = 295,
		Stand = 296,
		Think = 301
	}

	public const string RawName = "Regina Berry";

	public ReginaBerry(string username, ReginaBerryEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}