namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Richard Wellington
		Formatted Name: RichardWellington
		Emotion Count: 8
*/
public class RichardWellington : Character<RichardWellington.RichardWellingtonEmotions>
{
	public enum RichardWellingtonEmotions
	{
		Angry = 371,
		Breakdown = 372,
		Cornered = 377,
		Cornered2 = 376,
		Crazy = 375,
		Damage = 374,
		Shrug = 378,
		Stand = 373
	}

	public const string RawName = "Richard Wellington";

	public RichardWellington(string username, RichardWellingtonEmotions emotion, string text) : base(username, emotion,
		text)
	{
	}
}