namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Ron DeLite
		Formatted Name: RonDeLite
		Emotion Count: 7
*/
public class RonDeLite : Character<RonDeLite.RonDeLiteEmotions>
{
	public enum RonDeLiteEmotions
	{
		Cornered = 332,
		Sad = 331,
		Serious = 337,
		Shout = 336,
		Shout2 = 335,
		Stand = 333,
		Think = 334
	}

	public const string RawName = "Ron DeLite";

	public RonDeLite(string username, RonDeLiteEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}