namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Shelly de Killer (radio)
		Formatted Name: ShellyDeKillerRadio
		Emotion Count: 4
*/
public class ShellyDeKillerRadio : Character<ShellyDeKillerRadio.ShellyDeKillerRadioEmotions>
{
	public enum ShellyDeKillerRadioEmotions
	{
		Angry = 327,
		Break = 329,
		Cornered = 330,
		Stand = 328
	}

	public const string RawName = "Shelly de Killer (radio)";

	public ShellyDeKillerRadio(string username, ShellyDeKillerRadioEmotions emotion, string text) : base(username,
		emotion, text)
	{
	}
}