namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Shelly de Killer
		Formatted Name: ShellyDeKiller
		Emotion Count: 3
*/
public class ShellyDeKiller : Character<ShellyDeKiller.ShellyDeKillerEmotions>
{
	public enum ShellyDeKillerEmotions
	{
		Stand = 618,
		StandRedLight = 619,
		StandWaiter = 617
	}

	public const string RawName = "Shelly de Killer";

	public ShellyDeKiller(string username, ShellyDeKillerEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}