namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Spark Brushel
		Formatted Name: SparkBrushel
		Emotion Count: 7
*/
public class SparkBrushel : Character<SparkBrushel.SparkBrushelEmotions>
{
	public enum SparkBrushelEmotions
	{
		Cornered = 710,
		Damage = 750,
		Smile = 708,
		Sniff = 711,
		Stand = 709,
		Surprised = 752,
		Think = 751
	}

	public const string RawName = "Spark Brushel";

	public SparkBrushel(string username, SparkBrushelEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}