namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Terry Fawles
		Formatted Name: TerryFawles
		Emotion Count: 10
*/
public class TerryFawles : Character<TerryFawles.TerryFawlesEmotions>
{
	public enum TerryFawlesEmotions
	{
		Cough = 625,
		Cough2 = 620,
		CoughBlood = 629,
		Cry = 622,
		LookAway = 623,
		Nervous = 621,
		Serious = 624,
		SeriousBled = 628,
		Stand = 627,
		Yell = 626
	}

	public const string RawName = "Terry Fawles";

	public TerryFawles(string username, TerryFawlesEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}