namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: The Judge (AJ)
		Formatted Name: TheJudgeAJ
		Emotion Count: 6
*/
public class TheJudgeAJ : Character<TheJudgeAJ.TheJudgeAJEmotions>
{
	public enum TheJudgeAJEmotions
	{
		EyesClosed = 608,
		Headshake = 606,
		Negative = 609,
		Positive = 607,
		Stand = 611,
		Surprised = 610
	}

	public const string RawName = "The Judge (AJ)";

	public TheJudgeAJ(string username, TheJudgeAJEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}