namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: The Judge
		Formatted Name: TheJudge
		Emotion Count: 6
*/
public class TheJudge : Character<TheJudge.TheJudgeEmotions>
{
	public enum TheJudgeEmotions
	{
		EyesClosed = 32,
		Headshake = 30,
		Negative = 44,
		Positive = 31,
		Stand = 604,
		Surprised = 186
	}

	public const string RawName = "The Judge";

	public TheJudge(string username, TheJudgeEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}