namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Trucy Wright
		Formatted Name: TrucyWright
		Emotion Count: 4
*/
public class TrucyWright : Character<TrucyWright.TrucyWrightEmotions>
{
	public enum TrucyWrightEmotions
	{
		Determined = 561,
		Side = 560,
		Stand = 563,
		Think = 562
	}

	public const string RawName = "Trucy Wright";

	public TrucyWright(string username, TrucyWrightEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}