namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Vera Misham
		Formatted Name: VeraMisham
		Emotion Count: 14
*/
public class VeraMisham : Character<VeraMisham.VeraMishamEmotions>
{
	public enum VeraMishamEmotions
	{
		BiteNail = 444,
		Cornered = 457,
		Damage = 454,
		EyesClosed = 455,
		Happy = 453,
		Scared = 456,
		Sketch = 452,
		SketchAngry = 449,
		SketchApollo = 446,
		SketchHappy = 445,
		SketchSad = 450,
		SketchSurprised = 448,
		SketchTrucy = 447,
		Stand = 451
	}

	public const string RawName = "Vera Misham";

	public VeraMisham(string username, VeraMishamEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}