namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Victor Kudo
		Formatted Name: VictorKudo
		Emotion Count: 7
*/
public class VictorKudo : Character<VictorKudo.VictorKudoEmotions>
{
	public enum VictorKudoEmotions
	{
		Angry = 385,
		Pumped = 381,
		Shy = 379,
		Side = 380,
		Stand = 384,
		Surprised = 382,
		Throw = 383
	}

	public const string RawName = "Victor Kudo";

	public VictorKudo(string username, VictorKudoEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}