namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Viola Cadaverini
		Formatted Name: ViolaCadaverini
		Emotion Count: 3
*/
public class ViolaCadaverini : Character<ViolaCadaverini.ViolaCadaveriniEmotions>
{
	public enum ViolaCadaveriniEmotions
	{
		Cry = 680,
		Laugh = 681,
		Stand = 682
	}

	public const string RawName = "Viola Cadaverini";

	public ViolaCadaverini(string username, ViolaCadaveriniEmotions emotion, string text) : base(username, emotion,
		text)
	{
	}
}