namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Winfred Kitaki
		Formatted Name: WinfredKitaki
		Emotion Count: 3
*/
public class WinfredKitaki : Character<WinfredKitaki.WinfredKitakiEmotions>
{
	public enum WinfredKitakiEmotions
	{
		Brows = 722,
		Serious = 724,
		Stand = 723
	}

	public const string RawName = "Winfred Kitaki";

	public WinfredKitaki(string username, WinfredKitakiEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}