namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Winston Payne (old)
		Formatted Name: WinstonPayneOld
		Emotion Count: 6
*/
public class WinstonPayneOld : Character<WinstonPayneOld.WinstonPayneOldEmotions>
{
	public enum WinstonPayneOldEmotions
	{
		Confident = 438,
		Cornered = 441,
		Damage = 443,
		DamageCustom = 442,
		Smug = 440,
		Stand = 439
	}

	public const string RawName = "Winston Payne (old)";

	public WinstonPayneOld(string username, WinstonPayneOldEmotions emotion, string text) : base(username, emotion,
		text)
	{
	}
}