namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Winston Payne (young)
		Formatted Name: WinstonPayneYoung
		Emotion Count: 8
*/
public class WinstonPayneYoung : Character<WinstonPayneYoung.WinstonPayneYoungEmotions>
{
	public enum WinstonPayneYoungEmotions
	{
		Breakdown = 570,
		Confident = 564,
		Cornered = 568,
		CorneredHairless = 567,
		Damage = 571,
		DamageCustom = 566,
		Stand = 565,
		StandHairless = 569
	}

	public const string RawName = "Winston Payne (young)";

	public WinstonPayneYoung(string username, WinstonPayneYoungEmotions emotion, string text) : base(username, emotion,
		text)
	{
	}
}