namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Winston Payne
		Formatted Name: WinstonPayne
		Emotion Count: 5
*/
public class WinstonPayne : Character<WinstonPayne.WinstonPayneEmotions>
{
	public enum WinstonPayneEmotions
	{
		Confident = 19,
		Cornered = 410,
		Damage = 190,
		DamageCustom = 40,
		Stand = 20
	}

	public const string RawName = "Winston Payne";

	public WinstonPayne(string username, WinstonPayneEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}