namespace RandomGameBot.Features.ObjectionLol.Characters;

/*
	Auto generated by my random js script.
	Additional Information:
		Raw Name: Yanni Yogi
		Formatted Name: YanniYogi
		Emotion Count: 9
*/
public class YanniYogi : Character<YanniYogi.YanniYogiEmotions>
{
	public enum YanniYogiEmotions
	{
		Angry = 342,
		Fall = 339,
		LookAway = 338,
		Sad = 341,
		Serious = 345,
		Sleep = 346,
		Stand = 340,
		Think = 344,
		WakeUp = 343
	}

	public const string RawName = "Yanni Yogi";

	public YanniYogi(string username, YanniYogiEmotions emotion, string text) : base(username, emotion, text)
	{
	}
}